version: '3.8'

services:
  tile-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bing-tile-proxy
    restart: always
    environment:
      - PORT=8080
      - PYTHONUNBUFFERED=1
      - WORKERS=${WORKERS:-4}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    networks:
      - tile-network
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT:-1}'
          memory: ${MEMORY_LIMIT:-512M}
        reservations:
          cpus: '${CPU_RESERVATION:-0.5}'
          memory: ${MEMORY_RESERVATION:-256M}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/10/512/341.jpg"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    container_name: tile-proxy-nginx
    restart: always
    ports:
      - "${EXTERNAL_PORT:-8113}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-cache:/var/cache/nginx
    networks:
      - tile-network
    depends_on:
      - tile-server
    deploy:
      resources:
        limits:
          cpus: '${NGINX_CPU_LIMIT:-0.5}'
          memory: ${NGINX_MEMORY_LIMIT:-256M}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  tile-network:
    driver: bridge

volumes:
  nginx-cache:
    driver: local